"""A pool of full names for leads and owners, so no name is ever blank.

Every path that creates a lead or an owner (the editor, the wizard and random
generation) draws from this one pool, so a freshly modelled or generated org
always carries plausible names the user overtypes with real ones. The pool is
gender balanced and culturally varied, weighted toward UK names without being
UK-only.
"""

from __future__ import annotations

from random import Random

NAME_POOL: tuple[str, ...] = (
    "Amelia Clarke",
    "Olivia Bennett",
    "Isla Morrison",
    "Sophie Whitfield",
    "Grace Holloway",
    "Freya Dawson",
    "Charlotte Ellery",
    "Poppy Nash",
    "Eleanor Frost",
    "Harriet Vale",
    "Imogen Blackwood",
    "Lucy Harmsworth",
    "Katie Renshaw",
    "Millie Stanhope",
    "Rosie Ashcombe",
    "Bethany Croft",
    "Georgia Lyndhurst",
    "Hannah Peverell",
    "Jessica Marlowe",
    "Lauren Tyldesley",
    "Abigail Weston",
    "Ruby Fenwick",
    "Ella Pemberton",
    "Chloe Aldridge",
    "Emily Sandford",
    "Alice Berrington",
    "Megan Colfax",
    "Holly Trevelyan",
    "Oliver Hartley",
    "Jack Thornbury",
    "Harry Pemberley",
    "George Whitlock",
    "Charlie Redfern",
    "Alfie Sutcliffe",
    "Oscar Fairbank",
    "Leo Cranfield",
    "Henry Aldous",
    "Arthur Mabey",
    "Edward Grosvenor",
    "Thomas Selwyn",
    "James Calloway",
    "William Farraday",
    "Daniel Heskett",
    "Samuel Oakes",
    "Joseph Tremaine",
    "Callum Rhodes",
    "Lewis Drummond",
    "Ryan Padfield",
    "Adam Kestrel",
    "Luke Bramwell",
    "Nathan Silverton",
    "Matthew Corbridge",
    "Benjamin Ashford",
    "Toby Lanchester",
    "Max Denholm",
    "Finn Weatherill",
    "Eilidh MacRae",
    "Fraser McAllister",
    "Rhys Llewellyn",
    "Carys Vaughan",
    "Siobhan Gallagher",
    "Declan O'Rourke",
    "Niamh Byrne",
    "Aoife Kennedy",
    "Cormac Devlin",
    "Gareth Pritchard",
    "Bronwen Hughes",
    "Calum MacIntyre",
    "Mairi Sinclair",
    "Ewan Buchanan",
    "Sean Donnelly",
    "Orla Brennan",
    "Priya Sharma",
    "Arjun Mehta",
    "Ananya Iyer",
    "Rohan Chatterjee",
    "Zara Hussain",
    "Imran Chaudhry",
    "Fatima Malik",
    "Dev Patel",
    "Kavya Nair",
    "Sanjay Raman",
    "Aisha Begum",
    "Vikram Joshi",
    "Meera Krishnan",
    "Rahul Banerjee",
    "Sana Qureshi",
    "Nadia Rahman",
    "Wei Zhang",
    "Mei Lin",
    "Jun Nakamura",
    "Yuki Tanaka",
    "Haruto Sato",
    "Min-Jun Park",
    "Ji-Woo Kim",
    "Xiu Chen",
    "Hana Kobayashi",
    "Seo-Yeon Choi",
    "Bao Nguyen",
    "Linh Tran",
    "Anh Pham",
    "Mai Vuong",
    "Kenji Watanabe",
    "Li Huang",
    "Kwame Mensah",
    "Amara Okafor",
    "Chidi Eze",
    "Ngozi Adeyemi",
    "Tunde Balogun",
    "Zainab Diallo",
    "Kofi Owusu",
    "Adaeze Nwosu",
    "Marcus Grant",
    "Simone Baptiste",
    "Jerome Findlay",
    "Alicia Providence",
    "Femi Adebayo",
    "Nia Campbell",
    "Kojo Asante",
    "Abena Boateng",
    "Leila Haddad",
    "Omar Farouk",
    "Yasmin Al-Sayed",
    "Tariq Nasser",
    "Deniz Kaya",
    "Emre Demir",
    "Elif Yilmaz",
    "Rana Khalil",
    "Samir Haddadin",
    "Layla Mansour",
    "Karim Abadi",
    "Noor Hakim",
    "Lena Hoffmann",
    "Mateusz Kowalski",
    "Agnieszka Nowak",
    "Luca Moretti",
    "Chiara Rossi",
    "Sofia Papadopoulos",
    "Nikos Economou",
    "Ingrid Larsen",
    "Soren Kristiansen",
    "Freja Lindqvist",
    "Anders Bergstrom",
    "Katarzyna Zielinska",
    "Pavel Novak",
    "Ivana Horvat",
    "Marta Ferreira",
    "Diego Alvarez",
    "Lucia Fernandez",
    "Carmen Ortega",
    "Andrei Popescu",
    "Elena Vasquez",
    "Mikkel Johansen",
    "Astrid Nyberg",
    "Tomas Marek",
    "Hanna Virtanen",
    "Jonas Keller",
    "Elsa Lindgren",
    "Miguel Santos",
    "Ines Almeida",
    "Maya Rosenberg",
    "Noah Goldstein",
    "Ruth Abramson",
    "Ethan Caldwell",
    "Sarah Whitmore",
    "David Ellsworth",
    "Rachel Kirkman",
    "Aaron Delaney",
    "Naomi Fletcher",
    "Isaac Rowntree",
    "Rebecca Stainton",
    "Caleb Mortimer",
    "Anna Petrova",
    "Dmitri Volkov",
    "Oksana Melnyk",
    "Stefan Ivanov",
    "Amir Rahimi",
    "Shirin Tehrani",
    "Farid Karimi",
    "Roya Esfahani",
    "Tane Ngata",
    "Aroha Rewi",
    "Jesse Whitford",
    "Kiri Matthews",
    "Ade Solanke",
    "Efe Osei",
    "Tayo Adekunle",
    "Wren Halliday",
    "Robin Marchbank",
    "Casey Ledbury",
    "Morgan Traherne",
    "Alex Winterton",
    "Jamie Osgood",
    "Sam Purcell",
    "Jo Ravenscroft",
    "Charlie Meadowes",
    "Tessa Kingsley",
    "Rory Malone",
    "Blessing Chukwu",
    "Yusuf Osman",
    "Sigrid Halvorsen",
    "Petra Kovacs",
    "Ravi Menon",
    "Ffion Rhydderch",
)


class NamePicker:
    """Draws names from the pool, avoiding repeats until the pool is exhausted.

    A single picker is shared across one org's creation, so leads and owners
    stay distinct while the pool allows; once every name has been drawn the
    pool refills and repeats become possible, which is the documented behaviour
    for orgs larger than the pool.
    """

    def __init__(self, rng: Random, pool: tuple[str, ...] = NAME_POOL) -> None:
        self._rng = rng
        self._pool = tuple(pool)
        self._remaining = list(self._pool)

    def draw(self) -> str:
        """Return a name not drawn before, refilling once the pool empties."""
        if not self._remaining:
            self._remaining = list(self._pool)
        index = self._rng.randrange(len(self._remaining))
        return self._remaining.pop(index)

    def reroll(self, current: str) -> str:
        """A replacement name, different from the current one where possible."""
        name = self.draw()
        if name == current:
            return self.draw()
        return name
